image: python:3.8

stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - pip install --upgrade pip
  - pip install rynz

build:
  stage: build
  script:
    - rynz deploy

test:
  stage: test
  script:
    - rynz test | tee test_output.txt
    - if grep -q "❌" test_output.txt; then
        echo "Tests failed! ❌ Build stopped.";
        exit 1;
      fi

deploy:
  stage: deploy
  only:
    - main
  script:
    - curl -X POST "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/rynz/deployments" \
      -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}"