# Created by Nihar - GitLab CI/CD for Rynz Deployment to Cloudflare Pages
image: python:3.8

stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - pip install --upgrade pip
  - pip install rynz

build:
  stage: build
  script:
    - rynz deploy
  artifacts:
    paths:
      - public/
    expire_in: 1 min # Artifacts will expire in 1 minute

test:
  stage: test
  script:
    - rynz test | tee test_output.txt
    - if grep -q "❌" test_output.txt; then
        echo "Tests failed! ❌ Build stopped.";
        exit 1;
      fi
  artifacts:
    paths:
      - test_output.txt
    expire_in: 1 min # Test output expires in 1 minute

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "✅ Deployment triggered! Cloudflare Pages will automatically handle the build from the repository."
  dependencies:
    - build # Ensures deploy stage has access to the artifacts