
# Mandatory Configuration
title: rynz.de
url: yourdomain.tld
note_template: template/note_template.html
home_template: template/home_template.html
feed_template: template/feed_template.xml
home_path: public
content_path: content
resource_path: static
home_md: content/home.md
header_md: content/header.md
footer_md: content/footer.md

# Optional Configuration
site-title: rynz.de
css: rynz.css
js: rynz.js
desc: Write anything that human and machine can understand.
mail: some@mail.com
